services:
  prod:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - financiar_shared_network

  dev:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
      args:
        - VITE_SERVER_API=http://localhost:8000
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_SERVER_API=http://localhost:8000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        - action: rebuild
          path: ./vite.config.ts
          target: /app/vite.config.ts
    networks:
      - financiar_shared_network

networks:
  financiar_shared_network:
    external: true